Epam.Library/Epam.Library.MVC/Controllers/LibraryObjectController.cs
using Epam.Library.Core.Services;
using Epam.Library.Entities;
using Epam.Library.LogicContracts;
using Epam.Library.ViewModels.Display;
using PagedList;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Epam.Library.MVC.Controllers
{
    public class LibraryObjectController : Controller
    {
        private readonly GetAllService _getAllService;
        private List<DisplayLibraryObjectVM> _libraryObjects;
        private const int pageSize = 2;
        private readonly int maxPageNumber;

        // GET: LibraryObject
        private readonly ILibraryObjectLogic _libraryObjectLogic;
        public LibraryObjectController()
        {
            _getAllService = new GetAllService(Dependencies.DependencyResolver.Mapper);
            _libraryObjectLogic = Dependencies.DependencyResolver.LibraryObjectLogic;
            maxPageNumber = _getAllService.DisplayList(_libraryObjectLogic.GetAll()).Count;
            if (maxPageNumber % pageSize != 0)
            {
                maxPageNumber = (maxPageNumber / pageSize) + 1;
            }
            else
            {
                maxPageNumber /= pageSize;
            }
        }
        public ActionResult ShowLibraryObjects(int? page, bool? sortDirect, bool? sortReverse)
        {
            int pageNumber = page ?? 1;

            if (sortDirect != null && (bool)sortDirect)
            {
                _libraryObjects = _getAllService.DisplayList(_libraryObjectLogic.SelectLibraryObjectsForPageSortByYearDirect(pageNumber, pageSize));
                ViewBag.SortDirect = true;
            }
            else if (sortReverse != null && (bool)sortReverse)
            {
                _libraryObjects = _getAllService.DisplayList(_libraryObjectLogic.SelectLibraryObjectsForPageSortByYearReverse(pageNumber, pageSize));
                ViewBag.SortReverse = true;
            }
            else
            {
                _libraryObjects = _getAllService.DisplayList(_libraryObjectLogic.SelectLibraryObjectsForPage(pageNumber, pageSize));
                ViewBag.SortDirect = false;
                ViewBag.SortReverse = false;
            }
            ViewBag.MaxPage = maxPageNumber;
            ViewBag.CurrentPage = pageNumber;

            return View(_libraryObjects);
        }


        public ActionResult DeleteLibraryObject(int id)
        {
            if (_libraryObjectLogic.Delete(id))
            {
                return RedirectToAction(nameof(LibraryObjectController.ShowLibraryObjects));
            }
            else
            {
                return RedirectToAction(nameof(LibraryObjectController.ShowLibraryObjects));
            }
        }

        public ActionResult CheckLibraryObjectLikeDeleted(int id)
        {
            if (_libraryObjectLogic.CheckObjectLikeDeletedById(id))
            {
                return RedirectToAction(nameof(LibraryObjectController.ShowLibraryObjects));
            }
            else
            {
                return RedirectToAction(nameof(LibraryObjectController.ShowLibraryObjects));
            }
        }

        public ActionResult RestoreLibraryObject(int id)
        {
            if (_libraryObjectLogic.RestoreObject(id))
            {
                return RedirectToAction(nameof(LibraryObjectController.ShowLibraryObjects));
            }
            else
            {
                return RedirectToAction(nameof(LibraryObjectController.ShowLibraryObjects));
            }
        }

        [HttpPost]
        public ActionResult ShowByTitleLibraryObject(string title, int? page)
        {
            if (string.IsNullOrEmpty(title))
            {
                title = "No title";
            }
            int pageNumber = page ?? 1;
            _libraryObjects = _getAllService.DisplayList(_libraryObjectLogic.GetByTitle(title));
            ViewBag.MaxPage = maxPageNumber;
            ViewBag.CurrentPage = pageNumber;
            ViewBag.Title = title;

            return View(_libraryObjects);
        }

        public ActionResult GroupingByPublishingYear()
        {
            //return View(_showService.DisplayList(_libraryObjectLogic.GroupingByPublishingYear()));
            return View();
            //перевод
        }

        public ActionResult GetBooksPatentsByPerson(int personId)
        {
            return View(_getAllService.DisplayList(_libraryObjectLogic.GetBooksPatentsByPerson(personId)));
            //перевод
        }
    }
}

Epam.Library/Epam.Library.MVC/Views/Shared/CreateLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Library</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/css/bootstrap-select.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/js/bootstrap-select.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


</body>
</html>

Epam.Library/Epam.Library.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <form action="@Url.Action("ShowByTitleLibraryObject", "LibraryObject")" method="post">
            Title: <input type="text" name="title" /> <input type="submit" value="Find by title" />
        </form>

        @Html.ActionLink("Create new book", nameof(BookController.Create), nameof(Book))
        @Html.ActionLink("Create new patent", nameof(PatentController.Create), nameof(Patent))
        @Html.ActionLink("Create new newspaper", nameof(NewspaperController.Create), nameof(Newspaper))

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Library</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/css/bootstrap-select.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/js/bootstrap-select.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>
</html>

Epam.Library/Epam.Library.MVC/Views/Shared/_PartialShowLibraryObjects.cshtml
<div>
    @Html.ActionLink("Sort by year direct order", nameof(LibraryObjectController.ShowLibraryObjects), new { sortDirect = true, sortReverse = false })
</div>
<div>
    @Html.ActionLink("Sort by year reverse order", nameof(LibraryObjectController.ShowLibraryObjects), new { sortReverse = true, sortDirect = false })
</div>
<div>
    @Html.ActionLink("Without sort", nameof(LibraryObjectController.ShowLibraryObjects), new { sortDirect = false, sortReverse = false })
</div>